openapi: 3.0.0

info:
  title: Wazuh indexer API reference
  description: |
    The Wazuh indexer API is an open source RESTful API. It allows interaction with the Wazuh indexer from a web browser, command line tools like cURL or any script or program that can make web requests. The Wazuh indexer API is used to perform actions like adding and querying the indexes, modifying the Wazuh indexer settings, etc.

    # Authentication

    Wazuh indexer API endpoints require authentication to be used. There are multiple options on what authentication mechanism to use including basic HTTP authentication and JSON Web Token (JWT). More information can be seen in [Logging into the Wazuh indexer API](https://documentation.wazuh.com/current/user-manual/indexer-api/getting-started.html#logging-into-the-wazuh-indexer-api).
  version: 1.0.0

servers:
  - url: '{protocol}://{host}:{port}'
    description: Wazuh indexer API server
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
        description: Protocol for API communication
      host:
        default: localhost
        description: Hostname or IP address
      port:
        default: '9200'
        description: API port number

security:
  - basicAuth: []
  - jwtAuth: []

paths:
  /:
    get:
      tags:
        - Get API info
      summary: API info
      description: Return basic information about the API
      operationId: getApiInfo
      security:
        - basicAuth: []
        - jwtAuth: []
      parameters:
        - $ref: '#/components/parameters/pretty'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiInfo'
              example:
                name: "node-1"
                cluster_name: "wazuh-cluster"
                cluster_uuid: "XUqydNCQTuCnvtXobnRZ8w"
                version:
                  number: "7.10.2"
                  build_type: "deb"
                  build_hash: "9fd1835bba77ae04d48550eb4dc9be4787070806"
                  build_date: "2024-08-30T10:06:03.028357Z"
                  build_snapshot: false
                  lucene_version: "9.10.0"
                  minimum_wire_compatibility_version: "7.10.0"
                  minimum_index_compatibility_version: "7.0.0"
                tagline: "The OpenSearch Project: https://opensearch.org/"
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/ForbiddenApiInfo'

  /_analyze:
    get:
      tags: [Analyze API]
      summary: Text analysis (Global GET)
      description: |
        The analyze API endpoint enables text analysis by transforming unstructured text into individual tokens, typically words, optimized for search functionality. It processes a text string and returns the corresponding tokens as the output. It helps you debug and fine-tune text analysis settings for indexing and querying, providing insight into how text is broken into tokens and how filters are applied.
      operationId: analyzeGlobalGet
      parameters:
        - $ref: '#/components/parameters/analyzer'
        - $ref: '#/components/parameters/attributes'
        - $ref: '#/components/parameters/char_filter'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/normalizer'
        - $ref: '#/components/parameters/tokenizer'
        - $ref: '#/components/parameters/explain'
        - $ref: '#/components/parameters/pretty'
      requestBody:
        $ref: '#/components/requestBodies/AnalyzeRequest'
      responses:
        '200':
          $ref: '#/components/responses/AnalyzeSuccess'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
      security:
        - basicAuth: []
        - jwtAuth: []

    post:
      tags: [Analyze API]
      summary: Text analysis (Global POST)
      description: |
        The analyze API endpoint enables text analysis by transforming unstructured text into individual tokens, typically words, optimized for search functionality. It processes a text string and returns the corresponding tokens as the output. It helps you debug and fine-tune text analysis settings for indexing and querying, providing insight into how text is broken into tokens and how filters are applied.
      operationId: analyzeGlobalPost
      parameters:
        - $ref: '#/components/parameters/analyzer'
        - $ref: '#/components/parameters/attributes'
        - $ref: '#/components/parameters/char_filter'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/normalizer'
        - $ref: '#/components/parameters/tokenizer'
        - $ref: '#/components/parameters/explain'
        - $ref: '#/components/parameters/pretty'
      requestBody:
        $ref: '#/components/requestBodies/AnalyzeRequest'
      responses:
        '200':
          $ref: '#/components/responses/AnalyzeSuccess'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
      security:
        - basicAuth: []
        - jwtAuth: []

  /{index}/_analyze:
    parameters:
      - $ref: '#/components/parameters/index'
    get:
      tags: [Analyze API]
      summary: Text analysis (Index GET)
      description: |
        The analyze API endpoint enables text analysis by transforming unstructured text into individual tokens, typically words, optimized for search functionality. It processes a text string and returns the corresponding tokens as the output. It helps you debug and fine-tune text analysis settings for indexing and querying, providing insight into how text is broken into tokens and how filters are applied.
      operationId: analyzeIndexedGet
      parameters:
        - $ref: '#/components/parameters/analyzer'
        - $ref: '#/components/parameters/attributes'
        - $ref: '#/components/parameters/char_filter'
        - $ref: '#/components/parameters/field'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/normalizer'
        - $ref: '#/components/parameters/tokenizer'
        - $ref: '#/components/parameters/explain'
        - $ref: '#/components/parameters/pretty'
      requestBody:
        $ref: '#/components/requestBodies/AnalyzeRequest'
      responses:
        '200':
          $ref: '#/components/responses/AnalyzeSuccess'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
      security:
        - basicAuth: []
        - jwtAuth: []

    post:
      tags: [Analyze API]
      summary: Text analysis (Index POST)
      description: |
        The analyze API endpoint enables text analysis by transforming unstructured text into individual tokens, typically words, optimized for search functionality. It processes a text string and returns the corresponding tokens as the output. It helps you debug and fine-tune text analysis settings for indexing and querying, providing insight into how text is broken into tokens and how filters are applied.
      operationId: analyzeIndexedPost
      parameters:
        - $ref: '#/components/parameters/analyzer'
        - $ref: '#/components/parameters/attributes'
        - $ref: '#/components/parameters/char_filter'
        - $ref: '#/components/parameters/field'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/normalizer'
        - $ref: '#/components/parameters/tokenizer'
        - $ref: '#/components/parameters/explain'
        - $ref: '#/components/parameters/pretty'
      requestBody:
        $ref: '#/components/requestBodies/AnalyzeRequest'
      responses:
        '200':
          $ref: '#/components/responses/AnalyzeSuccess'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
      security:
        - basicAuth: []
        - jwtAuth: []

  /_search/scroll:
    get:
      tags: [Scroll]
      summary: Scroll search (GET)
      operationId: scrollSearchGet
      parameters:
        - $ref: '#/components/parameters/scroll'
        - $ref: '#/components/parameters/scroll_id'
        - $ref: '#/components/parameters/rest_total_hits_as_int'
      requestBody:
        $ref: '#/components/requestBodies/ScrollRequest'
      responses:
        '200':
          $ref: '#/components/responses/ScrollSuccess'
        '400':
          $ref: '#/components/responses/ScrollBadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
      security:
        - basicAuth: []
        - jwtAuth: []

    post:
      tags: [Scroll]
      summary: Scroll search (POST)
      operationId: scrollSearchPost
      parameters:
        - $ref: '#/components/parameters/scroll'
        - $ref: '#/components/parameters/scroll_id'
        - $ref: '#/components/parameters/rest_total_hits_as_int'
      requestBody:
        $ref: '#/components/requestBodies/ScrollRequest'
      responses:
        '200':
          $ref: '#/components/responses/ScrollSuccess'
        '400':
          $ref: '#/components/responses/ScrollBadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
      security:
        - basicAuth: []
        - jwtAuth: []

  /_search/scroll/<SCROLL_ID>:
    parameters:
      - $ref: '#/components/parameters/scroll_id_path'
    get:
      tags: [Scroll]
      summary: Scroll search by ID (GET)
      operationId: scrollSearchByIdGet
      parameters:
        - $ref: '#/components/parameters/scroll'
        - $ref: '#/components/parameters/rest_total_hits_as_int'
      requestBody:
        $ref: '#/components/requestBodies/ScrollRequestByID'
      responses:
        '200':
          $ref: '#/components/responses/ScrollSuccess'
        '400':
          $ref: '#/components/responses/ScrollBadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
      security:
        - basicAuth: []
        - jwtAuth: []

    post:
      tags: [Scroll]
      summary: Scroll search by ID (POST)
      operationId: scrollSearchByIdPost
      parameters:
        - $ref: '#/components/parameters/scroll'
        - $ref: '#/components/parameters/rest_total_hits_as_int'
      requestBody:
        $ref: '#/components/requestBodies/ScrollRequestByID'
      responses:
        '200':
          $ref: '#/components/responses/ScrollSuccess'
        '400':
          $ref: '#/components/responses/ScrollBadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
      security:
        - basicAuth: []
        - jwtAuth: []

components:
  parameters:
    index:
      name: index
      in: path
      required: true
      description: Target index name for analyzer derivation
      schema: { type: string }

    analyzer:
      name: analyzer
      in: query
      description: |
        The name of the analyzer to apply to the `text` field. The analyzer can be built in or configured in the index.

        If analyzer is not specified, the analyze API uses the analyzer defined in the mapping of the `field` field.
      schema: { type: string }

    attributes:
      name: attributes
      in: query
      description: Array of token attributes for filtering the output of the `explain` field.
      schema:
        type: array
        items: { type: string }
      style: form
      explode: true

    char_filter:
      name: char_filter
      in: query
      description: Array of character filters for preprocessing characters before the `tokenizer` field.
      schema:
        type: array
        items: { type: string }
      style: form
      explode: true

    field:
      name: field
      in: query
      description: |
        Field for deriving the analyzer.

        If you specify `field`, you must also specify the `index` path parameter.

        If you specify the `analyzer` field, it overrides the value of `field`.

        If you do not specify `field`, the analyze API uses the default analyzer for the index.

        If you do not specify the `index` field, or the index does not have a default analyzer, the analyze API uses the standard analyzer.
      schema: { type: string }

    filter:
      name: filter
      in: query
      description: Array of token filters to apply after the `tokenizer` field.
      schema:
        type: array
        items: { type: string }
      style: form
      explode: true

    normalizer:
      name: normalizer
      in: query
      description: Normalizer for converting text into a single token.
      schema: { type: string }

    tokenizer:
      name: tokenizer
      in: query
      description: Tokenizer for converting the text field into tokens.
      schema: { type: string }

    explain:
      name: explain
      in: query
      description: If `true`, causes the response to include token attributes and additional details.
      schema:
        type: boolean
        default: false

    pretty:
      name: pretty
      in: query
      description: Show results in human-readable format.
      schema:
        type: boolean
        default: false

    scroll:
      name: scroll
      in: query
      description: Specifies the amount of time the search context is maintained.
      schema:
        type: string
        format: time

    scroll_id:
      name: scroll_id
      in: query
      description: The scroll ID for the search.
      schema:
        type: string

    scroll_id_path:
      name: scroll_id
      in: path
      required: true
      description: The scroll ID for the search.
      schema:
        type: string

    rest_total_hits_as_int:
      name: rest_total_hits_as_int
      in: query
      description: Whether the `hits.total` property is returned as an integer (`true`) or an object (`false`).
      schema:
        type: boolean
        default: false

  schemas:
    ApiInfo:
      type: object
      properties:
        name:
          type: string
          description: The unique name of the specific Wazuh indexer node that responded to the request. In a multi-node cluster, this will be the name of the node that handled the request.
        cluster_name:
          type: string
          description: The name of the cluster which the Wazuh indexer is joined to.
        cluster_uuid:
          type: string
          description: A unique ID that identifies the Wazuh indexer node's cluster. This ID is generated when the cluster is first formed and remains constant.
        version:
          $ref: '#/components/schemas/VersionInfo'
        tagline:
          type: string
          description: Project description

    VersionInfo:
      type: object
      properties:
        number:
          type: string
          description: The version number of the Wazuh indexer node.
        build_type:
          type: string
          description: Describes how the build was packaged (e.g., `rpm`, `deb`, `tar`).
        build_hash:
          type: string
          description: A short hash of the Git commit from which this build was created. Useful for debugging and identifying the exact source code version.
        build_date:
          type: string
          format: date-time
          description: The date and time when this particular build was created.
        build_snapshot:
          type: boolean
          description: A boolean indicating if this is a snapshot build (development version) or a release build (`false` for releases).
        lucene_version:
          type: string
          description: The version of Apache Lucene, the underlying search library that Wazuh indexer uses.
        minimum_wire_compatibility_version:
          type: string
          description: The minimum version of Wazuh indexer that this node can communicate with over the network. Ensures backward compatibility.
        minimum_index_compatibility_version:
          type: string
          description: The minimum version of Wazuh indexer that this node can read indices created by. Ensures backward compatibility for stored data.

    AnalyzeRequest:
      type: object
      properties:
        text:
          oneOf:
            - type: string
            - type: array
              items:
                type: string
          description: Text to analyze. If you provide an array of strings, the text is analyzed as a multi-value field.

    Token:
      type: object
      properties:
        token:
          type: string
          description: The text fragment extracted during analysis. It is a word or part of a word.
        start_offset:
          type: integer
          description: The position in the input text where this token starts.
        end_offset:
          type: integer
          description: The position in the input text where this token ends.
        type:
          type: string
          description: The type of token inputted. This can be alphanumeric or custom depending on the analyzer.
        position:
          type: integer
          description: The position of the token in the sequence of tokens, starting from 0. This can help determine word order.

    AnalyzeResponse:
      type: object
      properties:
        analyzer:
          type: string
          description: The name of the analyzer applied to the query.
        text:
          type: string
          description: The text supplied to the query for analysis.
        tokens:
          type: array
          items: { $ref: '#/components/schemas/Token' }

    ScrollRequest:
      type: object
      properties:
        size:
          type: integer
          description: The number of documents to return per scroll request.
        query:
          type: object
          description: Defines the search criteria (e.g., `match`, `match_all`, `term`, etc.).
        sort:
          description: Defines how documents should be sorted (optional).
        _source:
          description: Controls which fields to return in the response.

    ScrollResponse:
      type: object
      properties:
        scroll:
          type: string
          format: time
          description: The scroll duration to keep the search context active.
        _scroll_id:
          type: string
          description: A unique identifier for retrieving the next batch of search results.
        took:
          type: integer
          description: The time (in milliseconds) it took Wazuh indexer to process the query.
        timed_out:
          type: boolean
          description: This indicates whether the query exceeded the timeout limit (`true` if the query timed out, `false` if it completed successfully).
        _shards:
          type: object
          properties:
            total:
              type: integer
              description: The total number of shards searched across the cluster for this query.
            successful:
              type: integer
              description: The number of shards that successfully executed the query.
            skipped:
              type: integer
              description: The number of shards skipped (if routing or index filtering is used).
            failed:
              type: integer
              description: The number of shards that encountered errors while processing the query.
        hits:
          type: object
          properties:
            total:
              type: object
              description: Provides information on the total number of matching documents.
              properties:
                value:
                  type: integer
                  description: The number of documents that match the query.
                relation:
                  type: string
                  description: The accuracy of the total value (`eq` means exact count, `gte` means "greater than or equal to" if the count was estimated).
            max_score:
              type: string
              description: The highest relevance score assigned to any matching document. A higher score means a closer match to the search query.

    SecurityError:
      type: object
      properties:
        error:
          type: object
          properties:
            root_cause:
              type: array
              items:
                type: object
                properties:
                  type: { type: string }
                  reason: { type: string }
            type: { type: string }
            reason: { type: string }
        status: { type: integer }

  requestBodies:
    AnalyzeRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AnalyzeRequest'
          example:
            analyzer: "standard"
            text: ["first array element", "second array element"]

    ScrollRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ScrollRequest'
          example:
            scroll: "20s"
            scroll_id: "FGluY2x1ZGVfY29udGV4dF91dWlkDnF1ZXJ5VGhlbkZldGNoAxZOcTlkTW9EblRBZXVObU5TbzlEdjhnAAAAAAAAEIAWdXlsbThKWnJRbHllSE53Ynl1UC01dxZOcTlkTW9EblRBZXVObU5TbzlEdjhnAAAAAAAAEH8WdXlsbThKWnJRbHllSE53Ynl1UC01dxZOcTlkTW9EblRBZXVObU5TbzlEdjhnAAAAAAAAEH4WdXlsbThKWnJRbHllSE53Ynl1UC01dw=="

    ScrollRequestByID:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ScrollRequest'
          example:
            scroll: "20s"

  responses:
    AnalyzeSuccess:
      description: Success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AnalyzeResponse'
          examples:
            standard:
              value:
                tokens:
                  - token: "test"
                    start_offset: 0
                    end_offset: 4
                    type: "<ALPHANUM>"
                    position: 0
                  - token: "word"
                    start_offset: 5
                    end_offset: 9
                    type: "<ALPHANUM>"
                    position: 1

    ScrollSuccess:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ScrollResponse'
          example:
            _scroll_id: "FGluY2x1ZGVfY29udGV4dF91dWlkDnF1ZXJ5VGhlbkZldGNoAxZOcTlkTW9EblRBZXVObU5TbzlEdjhnAAAAAAAAEIAWdXlsbThKWnJRbHllSE53Ynl1UC01dxZOcTlkTW9EblRBZXVObU5TbzlEdjhnAAAAAAAAEH8WdXlsbThKWnJRbHllSE53Ynl1UC01dxZOcTlkTW9EblRBZXVObU5TbzlEdjhnAAAAAAAAEH4WdXlsbThKWnJRbHllSE53Ynl1UC01dw=="
            took: 4
            timed_out: false
            _shards:
              total: 3
              successful: 3
              skipped: 0
              failed: 0
            hits:
              total:
                value: 183
                relation: "eq"
              max_score: 1
              hits: []

    BadRequest:
      description: Response to report a bad request
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  root_cause:
                    type: object
                    properties:
                      type: { type: string }
                      reason: { type: string }
              status: { type: integer }
          examples:
            missingText:
              value:
                error:
                  root_cause:
                    - type: "action_request_validation_exception"
                      reason: "Validation Failed: 1: text is missing;"
                  type: "action_request_validation_exception"
                  reason: "Validation Failed: 1: text is missing;"
                status: 400

    ScrollBadRequest:
      description: Response to report a bad request
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  root_cause:
                    type: object
                    properties:
                      type: { type: string }
                      reason: { type: string }
                  caused_by:
                    type: object
                    properties:
                      type: { type: string }
                      reason: { type: string }
              status: { type: integer }
          examples:
            scrollError:
              value:
                error:
                  root_cause:
                    - type: "illegal_argument_exception"
                      reason: "failed to parse [wazuh]"
                  type: "illegal_argument_exception"
                  reason: "failed to parse [wazuh]"
                  caused_by:
                    type: "number_format_exception"
                    reason: "For input string: \"wazu\""
                status: 400

    Unauthorized:
      description: Response to report an unauthorized request
      content:
        application/json:
          schema:
            type: object
            properties:
              root_cause:
                type: string
          example: "Unauthorized"

    ForbiddenApiInfo:
      description: Response to report a permission denied request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SecurityError'
          example:
            error:
              root_cause:
                - type: "security_exception"
                  reason: "no permissions for [/] and User [name=test, backend_roles=[], requestedTenant=null]"
              type: "security_exception"
              reason: "no permissions for [/] and User [name=test, backend_roles=[], requestedTenant=null]"
            status: 403

    Forbidden:
      description: Response to report a permission denied request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SecurityError'
          example:
            error:
              root_cause:
                - type: "security_exception"
                  reason: "no permissions for [indices:admin/analyze] and User [name=test, backend_roles=[], requestedTenant=null]"
              type: "security_exception"
              reason: "no permissions for [indices:admin/analyze] and User [name=test, backend_roles=[], requestedTenant=null]"
            status: 403

  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: Basic HTTP authentication
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT Bearer token authentication

tags:
  - name: Get API info
    description: Wazuh indexer API information
  - name: Analyze API
  - name: Scroll
    description: |
      You can utilize the scroll operation to obtain a substantial number of results. For instance, when looking for machine learning jobs, you can request an unlimited number of results in separate batches.

      To implement the scroll operation, include a scroll parameter in the request header along with a search context that indicates to the indexer how long you wish to continue scrolling. This search context should be sufficiently lengthy to allow for processing a single batch of results.

      Since search contexts can be memory-intensive, it's advisable to avoid using the scroll operation for frequent user queries. Instead, consider utilizing the sort parameter in conjunction with the search_after parameter to paginate through results for user queries.
